#This configuration file was written by: org.eclipse.equinox.internal.frameworkadmin.equinox.EquinoxFwConfigFileParser
#Fri Feb 23 15:06:33 UTC 2024
eclipse.product=org.omnetpp.main.product
osgi.splashPath=platform\:/base/plugins/org.omnetpp.main.omnetpp
org.eclipse.equinox.simpleconfigurator.configUrl=file\:org.eclipse.equinox.simpleconfigurator/bundles.info
osgi.bundles.defaultStartLevel=4
eclipse.application=org.eclipse.ui.ide.workbench
osgi.bundles=reference\:file\:org.eclipse.equinox.simpleconfigurator_1.5.0.v20230919-1457.jar@1\:start
eclipse.p2.data.area=@config.dir/../p2
eclipse.p2.profile=DefaultProfile
osgi.framework=file\:plugins/org.eclipse.osgi_3.18.600.v20231110-1900.jar
osgi.framework.extensions=reference\:file\:org.eclipse.osgi.compatibility.state_1.2.900.v20231106-0859.jar
eclipse.buildId=6.0.3.240223-17fcae5ef3
org.eclipse.update.reconcile=false
osgi.instance.area.default=../samples
